# Generated by Django 5.0.6 on 2024-05-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_date_time'],
            },
        ),
    ]
